### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by liamxg** [theosanderson/adhoc_covid#1]
ggplot(
+     data %>% filter(ltla %in% agg$ltla[1:32],epi_week>35, epi_week < 51, ltla != "NA"),
+     aes(x = epi_week_as_date, fill = b117)
+ ) + geom_bar(position = "fill",stat="identity") + facet_wrap( ~ ltla, scales = "free_y") +
+     theme_bw() + scale_fill_manual(values = c("darkgray", "darkred")) +
+     labs(fill = "B.1.1.7", y = "Relative frequency",x="Date (binned by epi-week)") + scale_y_continuous(labels = scales::percent)
Error: geom_bar requires the following missing aesthetics: y
Run `rlang::last_error()` to see where the error occurred.

**Comment by theosanderson** [comment]
Sorry this repo contains various scripts at various stages and some may be broken. It is mostly for visibility and I'm afraid I can't provide support.
